env: 
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci" 
   
    rclone_config: "ENCRYPTED[4d0278a2adf24e5d7f550ef9f2ec312ffea508a11a777aefc628f18f539e10d406a42096fbf30a6722a09c52085cc06d]"
    tg_auth: "ENCRYPTED[fc6f68050f9cddb2d95b8e4805526041b5a661f3ed8f7ffbaf8c88f8bb869e9dfbb22c01ec87e825eceeda39badad397]"
    
task:
    name: Kaneki Builder 
    timeout_in: 120m 
    container:
      dockerfile: Dockerfile 
      cpu: 8 
      memory: 32G 
    start_process_script:
      - ./1
    download_ccache_background_script:
      - ./2
    source_sync_script:
      - ./3
    monitor_ccache_background_script:
      - ./4
    rum_build_script:
      - ./5
 #   send_rum_script:
 #     - ./6
    upload_ccache_script:
      - ./7
