env: 
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci" 
   
    rclone_config: "ENCRYPTED[65e84d4b2f2235613a840d46e162163eca0377c43020fe09a5b59877a8862e939ce0f251c93900744d419c71fce12e9b]"
    tg_auth: "ENCRYPTED[040d3bded4d45f269aaeb31ce0b1906307b894b840fb5b39adf761a4fa6a7d6c8fb636b24a76d6b3d428f91d664a972a]"
    
task:
    name: Kaneki Builder 
    timeout_in: 140m 
    container:
      dockerfile: Dockerfile 
      cpu: 8 
      memory: 32G 
    start_process_script:
      - ./1
  #  download_ccache_background_script:
  #    - ./2
    source_sync_script:
      - ./3
    monitor_ccache_background_script:
      - ./4
    rum_build_script:
      - ./5
   # send_rum_script:
   #   - ./6
    upload_ccache_script:
      - ./7
