#!/bin/bash
mkdir -p /tmp/rom
cd /tmp/rom

# Repo init and sync
repo init -q --no-repo-verify --depth=1 -u https://github.com/Octavi-OS/platform_manifest.git -b 11 -g default,-device,-mips,-darwin,-notdefault

# Start repo sync
repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
repo sync -j1 --fail-fast

# Purge repo
rm -rf .repo

# Clone Device Sources
git clone --depth=1 https://github.com/Suraj-Sangwan/device_oneplus_fajita.git device/oneplus/fajita
git clone --depth=1 https://github.com/Suraj-Sangwan/device_oneplus_sdm845-common.git device/oneplus/sdm845-common
git clone --depth=1 https://github.com/Suraj-Sangwan/vendor_oneplus.git vendor/oneplus
git clone --depth=1 https://github.com/Suraj-Sangwan/device_oneplus_common.git device/oneplus/common
git clone --depth=1 https://github.com/Suraj-Sangwan/kernel_oneplus_sdm845.git kernel/oneplus/sdm845
git clone --depth=1 https://github.com/Suraj-Sangwan/vendor_addons_oneplus_apps.git vendor/addons/oneplus/apps

#Using own TouchGestures repo
rm -rf packages/apps/TouchGestures
git clone https://github.com/Suraj-Sangwan/packages_apps_TouchGestures.git packages/apps/TouchGestures