#!/bin/bash
cd /tmp/rom

# Notify In telegram
telegram -M "*PROJECTSAKURA ROM Compile Status*: \`STARTED!\`.
*Started at*:- \`$(date)\`."

# Normal build steps
build_start=$(date +"%s")
#
. build/envsetup.sh
lunch lineage_vince-user
export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 30G
ccache -o compression=true
ccache -z

# Start build
#mka sepolicy
#mka api-stubs-docs || echo no problem, we need ccache
#mka system-api-stubs-docs || echo no problem we need ccache
#mka test-api-stubs-docs || echo no problem, we need ccache
mka bacon -j16 &
sleep 65m
kill %1
#mka bacon -j16 | tee logs.txt
ccache -s
#
build_end=$(date +"%s")
echo "$((build_end - build_start))" > ~/.build_time
