#!/bin/bash
#
cd /tmp/rom
build_time=$(cat ~/.build_time)
build_name=$(ls /tmp/rom/out/target/product/fajita/ | grep -m1 -E 'fajita|.zip')
msd=$(cat /tmp/rom/out/target/product/fajita/$build_name.md5sum)

# Push Compiled ROM if available
if [ -f /tmp/rom/out/target/product/fajita/${build_name} ]; then

rclone copy /tmp/rom/out/target/product/fajita/$build_name fajita:/OctaviOS/ -P

telegram -M "*OCTAVI OS Compile Status*: \`FINISHED!\`
*Finished at*:- \`$(date)\`.
*Compile Time*: \`$((build_time / 3600)) hour(s), $((build_time % 3600 / 60)) minute(s) and $((build_time % 60)) seconds\`.
*Download Link*: [$build_name](https://hacks_on.susanoo-burner.workers.dev/OctaviOS/$build_name)
*Md5sum*: \`$(md5)\`
*CCache Stats*:-
\`$(ccache -s | sed -n -e "6,9 p" -e "9 q")\`"

else

telegram -M "*OCTAVI OS Compile Status*: \`FAILED!\`
*Failed at*:- \`$(date)\`.
*Compile Time*: \`$((build_time / 3600)) hour(s), $((build_time % 3600 / 60)) minute(s) and $((build_time % 60)) seconds\`.
*CCache Stats*:-
\`$(ccache -s | sed -n -e "6,9 p" -e "9 q")\`"
telegram -M -f logs.txt "*Here are the logs.*"
fi
